project:
  name: any3d

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

ejwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/any3d
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    jwt:
      enabled: true
      header: Authorization
      base64Secret: aG91c2VtZWFsZ3Jld21hc3Nwcml2YXRldGVycmlibGVmb290YmFsbGhhbGZ3YXliZWc=
      secret: 4322432423
      tokenValidityInSeconds: 1800
      tokenValidityInSecondsForRememberMe: 2592000
      anonymousUrls:
        - /public/**    # Example anonymous URL pattern
        - /login        # Another example
      permitAllUrls:
        - /permit/all/**   # Example permit all URL pattern
        - /public/**       # Another example
      authenticatedUrls:
        - /secure/**    # Example authenticated URL pattern
        - /api/**       # Another example

minio:
  url: http://localhost:9000
  username: minioadmin
  password: minioadmin

mybatis-plus:
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    call-setters-on-nulls: true
    use-column-label: true