project:
  name: any3d

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

ejwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/any3d
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    jwt:
      enabled: true
      header: Authorization
      base64Secret: "c2VjcmV0CmlkZW50aWZpZXJzCnNlY3JldA=="
      secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      tokenValidityInSeconds: 1800
      tokenValidityInSecondsForRememberMe: 2592000
      anonymousUrls:
        - /api/auth/login
        - /api/auth/register
      permitAllUrls:

      authenticatedUrls:
        - /api/users/**

minio:
  url: http://localhost:9000
  username: minioadmin
  password: minioadmin